/*
 * generated by Xtext 2.12.0
 */
package io.typefox.xtextxmi.xtree.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXtreeScopeProvider extends DelegatingScopeProvider {
}
