/*
 * generated by Xtext 2.12.0
 */
package io.typefox.xtextxmi.xtree.ui;

import com.google.inject.Injector;
import io.typefox.xtextxmi.xtree.ui.internal.XtreeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XtreeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtreeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtreeActivator.getInstance().getInjector(XtreeActivator.IO_TYPEFOX_XTEXTXMI_XTREE_XTREE);
	}
	
}
