/*
 * generated by Xtext 2.12.0
 */
package io.typefox.xtextxmi.xtree.parser.antlr;

import com.google.inject.Inject;
import io.typefox.xtextxmi.xtree.parser.antlr.internal.InternalXtreeParser;
import io.typefox.xtextxmi.xtree.services.XtreeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XtreeParser extends AbstractAntlrParser {

	@Inject
	private XtreeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXtreeParser createParser(XtextTokenStream stream) {
		return new InternalXtreeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Node";
	}

	public XtreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XtreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
