/*
 * generated by Xtext 2.12.0
 */
package io.typefox.xtextxmi.xtree.serializer;

import com.google.inject.Inject;
import io.typefox.xtextxmi.xtree.services.XtreeGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class XtreeSyntacticSequencer extends AbstractSyntacticSequencer {

	protected XtreeGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Node_ChildrenKeyword_1_2_0_q;
	protected AbstractElementAlias match_Node_RelatedKeyword_1_1_0_q;
	protected AbstractElementAlias match_Node___LeftParenthesisKeyword_1_0_RelatedKeyword_1_1_0_q_ChildrenKeyword_1_2_0_q_RightParenthesisKeyword_1_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (XtreeGrammarAccess) access;
		match_Node_ChildrenKeyword_1_2_0_q = new TokenAlias(false, true, grammarAccess.getNodeAccess().getChildrenKeyword_1_2_0());
		match_Node_RelatedKeyword_1_1_0_q = new TokenAlias(false, true, grammarAccess.getNodeAccess().getRelatedKeyword_1_1_0());
		match_Node___LeftParenthesisKeyword_1_0_RelatedKeyword_1_1_0_q_ChildrenKeyword_1_2_0_q_RightParenthesisKeyword_1_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNodeAccess().getLeftParenthesisKeyword_1_0()), new TokenAlias(false, true, grammarAccess.getNodeAccess().getRelatedKeyword_1_1_0()), new TokenAlias(false, true, grammarAccess.getNodeAccess().getChildrenKeyword_1_2_0()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getRightParenthesisKeyword_1_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Node_ChildrenKeyword_1_2_0_q.equals(syntax))
				emit_Node_ChildrenKeyword_1_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node_RelatedKeyword_1_1_0_q.equals(syntax))
				emit_Node_RelatedKeyword_1_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node___LeftParenthesisKeyword_1_0_RelatedKeyword_1_1_0_q_ChildrenKeyword_1_2_0_q_RightParenthesisKeyword_1_3__q.equals(syntax))
				emit_Node___LeftParenthesisKeyword_1_0_RelatedKeyword_1_1_0_q_ChildrenKeyword_1_2_0_q_RightParenthesisKeyword_1_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'children'?
	 *
	 * This ambiguous syntax occurs at:
	 *     related+=[Node|QualifiedName] (ambiguity) ')' (rule end)
	 */
	protected void emit_Node_ChildrenKeyword_1_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'related'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '(' (ambiguity) 'children' children+=Node
	 */
	protected void emit_Node_RelatedKeyword_1_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' 'related'? 'children'? ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_Node___LeftParenthesisKeyword_1_0_RelatedKeyword_1_1_0_q_ChildrenKeyword_1_2_0_q_RightParenthesisKeyword_1_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
