/*
 * generated by Xtext 2.12.0
 */
package io.typefox.xtextxmi.xtree.serializer;

import com.google.inject.Inject;
import io.typefox.xtextxmi.tree.Node;
import io.typefox.xtextxmi.tree.TreePackage;
import io.typefox.xtextxmi.xtree.services.XtreeGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class XtreeSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private XtreeGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TreePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TreePackage.NODE:
				sequence_Node(context, (Node) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Node returns Node
	 *
	 * Constraint:
	 *     (name=ID related+=[Node|QualifiedName]* children+=Node*)
	 */
	protected void sequence_Node(ISerializationContext context, Node semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
